<?php
/**
 * Sergei Krutov
 * Date: 7/23/14
 * Time: 9:46 PM
 */
return array(
	'allowedDomains' => array( // can login and modify profile
		'scryptmail.com'
	),
    'registeredDomain'=>'scryptmail.com',
	'planData'=>array(
        0=>array(
            'bSize'=>200,
            'cDomain'=>0,
            'alias'=>3,
            'pgpStr'=>2048,
            'attSize'=>10,
            'dispos'=>5,
            'pgpImport'=>0,
            'contactList'=>100,
            'delaySend'=>0,
            'sendLimits'=>20,
            'folderExpire'=>0,
            'recipPerMail'=>10,
            'secLog'=>1,
            'filter'=>50,
            'blackList'=>100,
            'price'=>0
        ),
        1=>array(
            'bSize'=>300,
            'cDomain'=>0,
            'alias'=>1,
            'pgpStr'=>2048,
            'attSize'=>10,
            'dispos'=>3,
            'pgpImport'=>0,
            'contactList'=>1000,
            'delaySend'=>0,
            'sendLimits'=>20,
            'folderExpire'=>1,
            'recipPerMail'=>10,
            'secLog'=>1,
            'filter'=>500,
            'blackList'=>2000,
            'price'=>200
        ),
        7=>array(
            'bSize'=>1000,
            'cDomain'=>2,
            'alias'=>5,
            'pgpStr'=>4096,
            'attSize'=>20,
            'dispos'=>10,
            'pgpImport'=>1,
            'contactList'=>2000,
            'delaySend'=>0,
            'sendLimits'=>40,
            'folderExpire'=>1,
            'recipPerMail'=>20,
            'secLog'=>1,
            'filter'=>1000,
            'blackList'=>5000,
            'price'=>700
        ),
        15=>array(
            'bSize'=>5000,
            'cDomain'=>5,
            'alias'=>10,
            'pgpStr'=>8192,
            'attSize'=>30,
            'dispos'=>20,
            'pgpImport'=>1,
            'contactList'=>4000,
            'delaySend'=>0,
            'sendLimits'=>60,
            'folderExpire'=>1,
            'recipPerMail'=>50,
            'secLog'=>1,
            'filter'=>5000,
            'blackList'=>10000,
            'price'=>1500
        ),
	),

	'tlds'=>array(
		'aaa','aarp','abb','abbott','abbvie','abogado','abudhabi','ac','academy','accenture','accountant','accountants','aco','active','actor','ad','adac','ads','adult','ae','aeg','aero','af','afl','ag','agakhan','agency','ai','aig','airforce','airtel','akdn','al','alibaba','alipay','allfinanz','ally','alsace','am','amica','amsterdam','analytics','android','anquan','ao','apartments','app','apple','aq','aquarelle','ar','aramco','archi','army','arpa','arte','as','asia','associates','at','attorney','au','auction','audi','audio','author','auto','autos','avianca','aw','aws','ax','axa','az','azure','ba','baby','baidu','band','bank','bar','barcelona','barclaycard','barclays','barefoot','bargains','bauhaus','bayern','bb','bbc','bbva','bcg','bcn','bd','be','beats','beer','bentley','berlin','best','bet','bf','bg','bh','bharti','bi','bible','bid','bike','bing','bingo','bio','biz','bj','black','blackfriday','bloomberg','blue','bm','bms','bmw','bn','bnl','bnpparibas','bo','boats','boehringer','bom','bond','boo','book','boots','bosch','bostik','bot','boutique','br','bradesco','bridgestone','broadway','broker','brother','brussels','bs','bt','budapest','bugatti','build','builders','business','buy','buzz','bv','bw','by','bz','bzh','ca','cab','cafe','cal','call','camera','camp','cancerresearch','canon','capetown','capital','car','caravan','cards','care','career','careers','cars','cartier','casa','cash','casino','cat','catering','cba','cbn','cc','cd','ceb','center','ceo','cern','cf','cfa','cfd','cg','ch','chanel','channel','chase','chat','cheap','chloe','christmas','chrome','church','ci','cipriani','circle','cisco','citic','city','cityeats','ck','cl','claims','cleaning','click','clinic','clinique','clothing','cloud','club','clubmed','cm','cn','co','coach','codes','coffee','college','cologne','com','commbank','community','company','compare','computer','comsec','condos','construction','consulting','contact','contractors','cooking','cool','coop','corsica','country','coupon','coupons','courses','cr','credit','creditcard','creditunion','cricket','crown','crs','cruises','csc','cu','cuisinella','cv','cw','cx','cy','cymru','cyou','cz','dabur','dad','dance','date','dating','datsun','day','dclk','de','dealer','deals','degree','delivery','dell','deloitte','delta','democrat','dental','dentist','desi','design','dev','diamonds','diet','digital','direct','directory','discount','dj','dk','dm','dnp','do','docs','dog','doha','domains','download','drive','dubai','durban','dvag','dz','earth','eat','ec','edeka','edu','education','ee','eg','email','emerck','energy','engineer','engineering','enterprises','epson','equipment','er','erni','es','esq','estate','et','eu','eurovision','eus','events','everbank','exchange','expert','exposed','express','extraspace','fage','fail','fairwinds','faith','family','fan','fans','farm','fashion','fast','feedback','ferrero','fi','film','final','finance','financial','firestone','firmdale','fish','fishing','fit','fitness','fj','fk','flickr','flights','florist','flowers','flsmidth','fly','fm','fo','foo','football','ford','forex','forsale','forum','foundation','fox','fr','fresenius','frl','frogans','frontier','ftr','fund','furniture','futbol','fyi','ga','gal','gallery','gallo','gallup','game','garden','gb','gbiz','gd','gdn','ge','gea','gent','genting','gf','gg','ggee','gh','gi','gift','gifts','gives','giving','gl','glass','gle','global','globo','gm','gmail','gmbh','gmo','gmx','gn','gold','goldpoint','golf','goo','goog','google','gop','got','gov','gp','gq','gr','grainger','graphics','gratis','green','gripe','group','gs','gt','gu','gucci','guge','guide','guitars','guru','gw','gy','hamburg','hangout','haus','hdfcbank','health','healthcare','help','helsinki','here','hermes','hiphop','hitachi','hiv','hk','hm','hn','hockey','holdings','holiday','homedepot','homes','honda','horse','host','hosting','hoteles','hotmail','house','how','hr','hsbc','ht','htc','hu','hyundai','ibm','icbc','ice','icu','id','ie','ifm','iinet','il','im','imamat','immo','immobilien','in','industries','infiniti','info','ing','ink','institute','insurance','insure','int','international','investments','io','ipiranga','iq','ir','irish','is','iselect','ismaili','ist','istanbul','it','itau','iwc','jaguar','java','jcb','jcp','je','jetzt','jewelry','jlc','jll','jm','jmp','jnj','jo','jobs','joburg','jot','joy','jp','jpmorgan','jprs','juegos','kaufen','kddi','ke','kerryhotels','kerrylogistics','kerryproperties','kfh','kg','kh','ki','kia','kim','kinder','kitchen','kiwi','km','kn','koeln','komatsu','kp','kpmg','kpn','kr','krd','kred','kuokgroup','kw','ky','kyoto','kz','la','lacaixa','lamborghini','lamer','lancaster','land','landrover','lanxess','lasalle','lat','latrobe','law','lawyer','lb','lc','lds','lease','leclerc','legal','lexus','lgbt','li','liaison','lidl','life','lifeinsurance','lifestyle','lighting','like','limited','limo','lincoln','linde','link','lipsy','live','living','lixil','lk','loan','loans','locus','lol','london','lotte','lotto','love','lr','ls','lt','ltd','ltda','lu','lupin','luxe','luxury','lv','ly','ma','madrid','maif','maison','makeup','man','management','mango','market','marketing','markets','marriott','mba','mc','md','me','med','media','meet','melbourne','meme','memorial','men','menu','meo','mg','mh','miami','microsoft','mil','mini','mk','ml','mls','mm','mma','mn','mo','mobi','mobily','moda','moe','moi','mom','monash','money','montblanc','mormon','mortgage','moscow','motorcycles','mov','movie','movistar','mp','mq','mr','ms','mt','mtn','mtpc','mtr','mu','museum','mutual','mutuelle','mv','mw','mx','my','mz','na','nadex','nagoya','name','natura','navy','nc','ne','nec','net','netbank','network','neustar','new','news','next','nextdirect','nexus','nf','ng','ngo','nhk','ni','nico','nikon','ninja','nissan','nissay','nl','no','nokia','northwesternmutual','norton','nowruz','np','nr','nra','nrw','ntt','nu','nyc','nz','obi','office','okinawa','olayan','om','omega','one','ong','onl','online','ooo','oracle','orange','org','organic','origins','osaka','otsuka','ovh','pa','page','pamperedchef','panerai','paris','pars','partners','parts','party','passagens','pe','pet','pf','pg','ph','pharmacy','philips','photo','photography','photos','physio','piaget','pics','pictet','pictures','pid','pin','ping','pink','pizza','pk','pl','place','play','playstation','plumbing','plus','pm','pn','pohl','poker','porn','post','pr','praxi','press','pro','prod','productions','prof','progressive','promo','properties','property','protection','ps','pt','pub','pw','pwc','py','qa','qpon','quebec','quest','racing','re','read','realtor','realty','recipes','red','redstone','redumbrella','rehab','reise','reisen','reit','ren','rent','rentals','repair','report','republican','rest','restaurant','review','reviews','rexroth','rich','ricoh','rio','rip','ro','rocher','rocks','rodeo','room','rs','rsvp','ru','ruhr','run','rw','rwe','ryukyu','sa','saarland','safe','safety','sakura','sale','salon','samsung','sandvik','sandvikcoromant','sanofi','sap','sapo','sarl','sas','saxo','sb','sbi','sbs','sc','sca','scb','schaeffler','schmidt','scholarships','school','schule','schwarz','science','scor','scot','sd','se','seat','security','seek','select','sener','services','seven','sew','sex','sexy','sfr','sg','sh','sharp','shaw','shell','shia','shiksha','shoes','shouji','show','shriram','si','sina','singles','site','sj','sk','ski','skin','sky','skype','sl','sm','smile','sn','sncf','so','soccer','social','softbank','software','sohu','solar','solutions','song','sony','soy','space','spiegel','spot','spreadbetting','sr','srl','st','stada','star','starhub','statebank','statefarm','statoil','stc','stcgroup','stockholm','storage','store','stream','studio','study','style','su','sucks','supplies','supply','support','surf','surgery','suzuki','sv','swatch','swiss','sx','sy','sydney','symantec','systems','sz','tab','taipei','talk','taobao','tatamotors','tatar','tattoo','tax','taxi','tc','tci','td','team','tech','technology','tel','telecity','telefonica','temasek','tennis','teva','tf','tg','th','thd','theater','theatre','tickets','tienda','tiffany','tips','tires','tirol','tj','tk','tl','tm','tmall','tn','to','today','tokyo','tools','top','toray','toshiba','total','tours','town','toyota','toys','tr','trade','trading','training','travel','travelers','travelersinsurance','trust','trv','tt','tube','tui','tunes','tushu','tv','tvs','tw','tz','ua','ubs','ug','uk','unicom','university','uno','uol','us','uy','uz','va','vacations','vana','vc','ve','vegas','ventures','verisign','versicherung','vet','vg','vi','viajes','video','vig','viking','villas','vin','vip','virgin','vision','vista','vistaprint','viva','vlaanderen','vn','vodka','volkswagen','vote','voting','voto','voyage','vu','vuelos','wales','walter','wang','wanggou','warman','watch','watches','weather','weatherchannel','webcam','weber','website','wed','wedding','weibo','weir','wf','whoswho','wien','wiki','williamhill','win','windows','wine','wme','wolterskluwer','work','works','world','ws','wtc','wtf','xbox','xerox','xihuan','xin','xperia','xxx','xyz','yachts','yahoo','yamaxun','yandex','ye','yodobashi','yoga','yokohama','you','youtube','yt','yun','za','zara','zero','zip','zm','zone','zuerich','zw'),
	'sufTlds'=>array(
		'ac','ad','ae','aero','af','ag','ai','al','am','ao','aq','ar','arpa','as','asia','at','au','aw','ax','az','ba','bb','bd','be','bf','bg','bh','bi','biz','bj','bm','bn','bo','br','bs','bt','bv','bw','by','bz','ca','cat','cc','cd','cf','cg','ch','ci','ck','cl','cm','cn','co','com','coop','cr','cu','cv','cw','cx','cy','cz','de','dj','dk','dm','do','dz','ec','edu','ee','eg','er','es','et','eu','fi','fj','fk','fm','fo','fr','ga','gb','gd','ge','gf','gg','gh','gi','gl','gm','gn','gov','gp','gq','gr','gs','gt','gu','gw','gy','hk','hm','hn','hr','ht','hu','id','ie','il','im','in','info','int','io','iq','ir','is','it','je','jm','jo','jobs','jp','ke','kg','kh','ki','km','kn','kp','kr','kw','ky','kz','la','lb','lc','li','lk','lr','ls','lt','lu','lv','ly','ma','mc','md','me','mg','mh','mil','mk','ml','mm','mn','mo','mobi','mp','mq','mr','ms','mt','mu','museum','mv','mw','mx','my','mz','na','name','nc','ne','net','nf','ng','ni','nl','no','np','nr','nu','nz','om','org','pa','pe','pf','pg','ph','pk','pl','pm','pn','post','pr','pro','ps','pt','pw','py','qa','re','ro','rs','ru','rw','sa','sb','sc','sd','se','sg','sh','si','sj','sk','sl','sm','sn','so','sr','st','su','sv','sx','sy','sz','tc','td','tel','tf','tg','th','tj','tk','tl','tm','tn','to','tr','travel','tt','tv','tw','tz','ua','ug','uk','us','uy','uz','va','vc','ve','vg','vi','vn','vu','wf','ws','yt','срб','xxx','ye','za','zm','zw'

	)
);